---
- name: Play for Install Nginx on WebServers
  hosts: localhost
  gather_facts: yes
  vars:
    custom_heading: "Welcome To Autoscaling Testing by manisarath284"
    todays_date: "{{ ansible_facts['date_time']['date'] }}"
    host_name: "{{ ansible_facts['hostname'] }}"
    fqdn_name: "{{ ansible_facts['fqdn'] }}"
    ip_address: "{{ ansible_default_ipv4.address }}"
  tasks:
    - name: Run Apt Update
      become: yes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install python3-apt
      become: yes
      apt:
        name: python3-apt
        state: present

    - name: Install Nginx Server
      become: yes
      apt:
        name: nginx
        state: present

    - name: Copy the index template
      become: yes
      template:
        src: /myrepo/index.j2
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0644'

    - name: Copy the style file
      become: yes
      copy:
        src: /myrepo/style.css
        dest: /var/www/html/style.css
        owner: root
        group: root
        mode: '0644'

    - name: Copy the javascript file
      become: yes
      copy:
        src: /myrepo/scorekeeper.js
        dest: /var/www/html/scorekeeper.js
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx
      become: yes
      service:
        name: nginx
        state: restarted
